version : '3'
services:
  web:
    build : 
      # Specifies path to build image from
      context : .
      dockerfile : Dockerfile.dev
    ports :
      - "3000:3000"
    volumes :
      - /app/node_modules
      - .:/app
